//alkuperäisen pelin pelaaja database, oisko jako hinnan mukaan vai pelipaikan? ehkä hinnan? hinnan muut paitsi jokerit erikseen?

let lukkarit = {
	Nyman: {
        	pelipaikka: lukkari,
		palkka: 5000,
       		etunimi: 'Alpo',
        	lyöMin: 1,
      		lyöMax: 9,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 17-18,
		up: 14-18,
	},
	Koskela: {
        	pelipaikka: lukkari,
		palkka: 5000,
       		etunimi: 'Jaakko',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 16-18,
		up: 15-18,
	}
}

let etukenttä = {
	Rantamäki: {
        	pelipaikka: etukenttä,
		palkka: 5000,
       		etunimi: 'Lassi',
        	lyöMin: 1,
      		lyöMax: 9,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 17-18,
		up: 15-18,
	},
	Salomaa: {
        	pelipaikka: etukenttä,
		palkka: 5000,
       		etunimi: 'Riku',
        	lyöMin: 1,
      		lyöMax: 8,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: true,
		sp: 16-18,
		up: 15-18,
	},
	Hulkkonen: {
        	pelipaikka: etukenttä,
		palkka: 5000,
       		etunimi: 'Matti',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 15-18,
		up: 16-18,
	},
	Lähde: {
        	pelipaikka: etukenttä,
		palkka: 5000,
       		etunimi: 'Risto',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 16-18,
		up: 17-18,
	},
	Koljonen: {
        	pelipaikka: etukenttä,
		palkka: 5000,
       		etunimi: 'Armas',
        	lyöMin: 1,
      		lyöMax: 9,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 16-18,
		up: 16-18,
	},
	Ekqvist: {
        	pelipaikka: etukenttä,
		palkka: 5000,
       		etunimi: 'Matti',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 16-18,
		up: 16-18,
	}
}

let polttolinja = {
	Lampi: {
        	pelipaikka: polttolinja,
		palkka: 5000,
       		etunimi: 'Kalevi',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 17-18,
		up: 16-18,
	},
	Närhi: {
        	pelipaikka: polttolinja,
		palkka: 5000,
       		etunimi: 'Jaakko',
        	lyöMin: 1,
      		lyöMax: 9,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 17-18,
		up: 14-18,
	},
	Toivola: {
        	pelipaikka: polttolinja,
		palkka: 5000,
       		etunimi: 'Olli',
        	lyöMin: 1,
      		lyöMax: 9,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: true,
		sp: 15-18,
		up: 16-18,
	},
	Niiranen: {
        	pelipaikka: polttolinja,
		palkka: 5000,
       		etunimi: 'Sakari',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 15-18,
		up: 17-18,
	},
	Tuunanen: {
        	pelipaikka: polttolinja,
		palkka: 5000,
       		etunimi: 'Hannu',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 15-18,
		up: 16-18,
	},
	Raivio: {
        	pelipaikka: polttolinja,
		palkka: 5000,
       		etunimi: 'Valtteri',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 14-18,
		up: 16-18,
	},
	Kärkinen: {
        	pelipaikka: polttolinja,
		palkka: 5000,
       		etunimi: 'Kari',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 17-18,
		up: 16-18,
	},
	Lehto: {
        	pelipaikka: polttolinja,
		palkka: 5000,
       		etunimi: 'Veijo',
        	lyöMin: 1,
      		lyöMax: 9,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 17-18,
		up: 17-18,
	},
	Lindström: {
        	pelipaikka: polttolinja,
		palkka: 5000,
       		etunimi: 'Ilkka',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 16-18,
		up: 16-18,
	},
	Raski: {
        	pelipaikka: polttolinja,
		palkka: 5000,
       		etunimi: 'Jaakko',
        	lyöMin: 1,
      		lyöMax: 11,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 15-18,
		up: 17-18,
	}
}

let takakenttä = {
	Mäki: {
        	pelipaikka: takakenttä,
		palkka: 5000,
       		etunimi: 'Aapeli',
        	lyöMin: 1,
      		lyöMax: 9,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 17-18,
		up: 17-18,
	},
	Kivimäki: {
        	pelipaikka: takakenttä,
		palkka: 5000,
       		etunimi: 'Arto',
        	lyöMin: 1,
      		lyöMax: 8,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: true,
		sp: 16-18,
		up: 16-18,
	}, 
	Ö: {
        	pelipaikka: takakenttä,
		palkka: 5000,
       		etunimi: 'Bo',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 16-18,
		up: 16-18,
	},
	Siltanen: {
        	pelipaikka: takakenttä,
		palkka: 5000,
       		etunimi: 'Timo',
        	lyöMin: 1,
      		lyöMax: 9,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 17-18,
		up: 15-18,
	},
	Alajoki: {
        	pelipaikka: takakenttä,
		palkka: 5000,
       		etunimi: 'Taito',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 15-18,
		up: 16-18,
	},
	Saha: {
        	pelipaikka: takakenttä,
		palkka: 5000,
       		etunimi: 'Markku',
        	lyöMin: 1,
      		lyöMax: 10,
       		lyöKahdesti: false,
       		lyöJokereita: false,
		lyöÄssiä: false,
		sp: 17-18,
		up: 14-18,
	}
}

