//alkuperäisen pelin pelaaja database, oisko jako hinnan mukaan vai pelipaikan? ehkä hinnan? hinnan muut paitsi jokerit erikseen?

let vimpeli = { //joukkueen pelaajat ja statsit
    pelaajat: {
        lukkari: {
            nimi: 'Kinnunen',
            lyöMin: 2,
            lyöMax: 12,
            lyöKahdesti: false,
            lyöJokereita: false,
		lyöÄssiä: false,
        },
        sieppari: {
            nimi: 'Rinta-aho',
            lyöMin: 1,
            lyöMax: 13,
            lyöKahdesti: false,
            lyöJokereita: false,
		lyöVäriä: true,
		lyöÄssiä: true,
        },
        ykkösvahti: {
            nimi: 'S. Lassila',
            lyöMin: 1,
            lyöMax: 13,
            lyöKahdesti: false,
            lyöJokereita: false,
		lyöVäriä: false,
		lyöÄssiä: true,
        },
        kakkosvahti: {
            nimi: 'L. Vihriälä',
            lyöMin: 2,
            lyöMax: 13,
            lyöKahdesti: false,
            lyöJokereita: false,
		lyöVäriä: false,
		lyöÄssiä: false,
        },
        kakkospolttaja: {
            nimi: 'J. Heikkala',
            lyöMin: 2,
            lyöMax: 12,
            lyöKahdesti: false,
            lyöJokereita: false,
		lyöVäriä: false,
		lyöÄssiä: false,
        },
        kolmospolttaja: {
            nimi: 'O. Heikkala',
            lyöMin: 2,
            lyöMax: 12,
            lyöKahdesti: false,
            lyöJokereita: false,
		lyöVäriä: false,
		lyöÄssiä: false,
        },
        kolmosvahti: {
            nimi: 'A. Lassila',
            lyöMin: 1,
            lyöMax: 13,
            lyöKahdesti: false,
            lyöJokereita: false,
		lyöVäriä: false,
		lyöÄssiä: true,
        },
        kakkoskoppari: {
            nimi: 'M. Vihriälä',
            lyöMin: 2,
            lyöMax: 13,
            lyöKahdesti: false,
            lyöJokereita: false,
		lyöVäriä: false,
		lyöÄssiä: false,
        },
        kolmoskoppari: {
            nimi: 'Anttila',
            lyöMin: 1,
            lyöMax: 13,
            lyöKahdesti: false,
            lyöJokereita: false,
		lyöVäriä: true,
		lyöÄssiä: true,
        },
        jokeri: {
            nimi: 'Vainionpää',
            lyöMin: 1,
            lyöMax: 13,
            lyöKahdesti: true,
            lyöJokereita: true,
		lyöVäriä: true,
		lyöÄssiä: true,
        }
    } 
}
